name: Build Unity WebGL and Deploy to Netlify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-actions/setup@v3
        with:
          unityVersion: 2022.3.50f1 # プロジェクトに合わせてUnityバージョンを変更

      # 必要であればライセンスのアクティベート
      # - name: Activate Unity License
      #   uses: game-ci/unity-actions/activate@v3
      #   with:
      #     unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Build WebGL
        uses: game-ci/unity-actions/build@v3
        with:
          targetPlatform: WebGL

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --dir=build/WebGL --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID